### PR TITLE
escape schema/table/view identifier

### PR DESCRIPTION
**Pull request by soleuu**
Some identifier escape are missing and make wrong request.

### CODE REVIEW

**Comment by xzilla** [comment]
This change looks ok, but I couldn't actually trigger a bug with the existing code. Do you have an example? I'm thinking it might be good to update the test suite for this in the future.

**Comment by soleuu** [comment]
You need to create object (schema/table/view) with upper case letter for exemple.
The problem apprear on Table/Browse, it will construct a query without double quotes and postgresql with interpret them as lower cased object when executed.

example:
create table "FooBar" (....);

**Comment by xzilla** [comment]
I think I have verified the problem, but the fix doesn't fix it on my setup. I think that is due to some other nearby bugs, or possibly some version differences. Can you LMK what versions of PHP and Postgres you are testing with?

**Comment by xzilla** [comment]
This was committed and pushed to master. Closing since github didn't auto-close it. Thanks for the submission!

**Pull request closed without merging**
