### PR TITLE
Update jquery

### PR DESCRIPTION
**Pull request by nirgal**
I used the Debian version, that is slightly different from the original
https://code.jquery.com/jquery-3.3.1.js

### CODE REVIEW

**Comment by thetuxinator** [comment]
Even better would be to maybe use something fast, like http://velocityjs.org/ ;-)

**Comment by nirgal** [comment]
I ran the selenium tests with regular jquery 3.4.1 from https://code.jquery.com/ and it worked ok (running postgresql 12). I'll update that PR.

**Comment by xzilla** [comment]
What browser are you working with? When I tested this code, it fails for the process tracking and locks tracking at the database level (it should fail in selenium testing, or at least, it does for me).

**Comment by nirgal** [comment]
I did test version 3.4.1 with chromium with both PG11 and PG12, or so I though, but I confirm that now the selenium tests are failing here too, both with firefox and chromium. I don't quite know how this could happen, sorry about that. I just noticed that changing the server side jquery required some cache flushing on the client side, and it might be the cause of the issue not being visible here.

Anyway, with the new jquery, the first failure is in "Admin tests": When you click on a database on the left tree, then on "Process", the selenium tests expect the "Start" link to be there, but it's already gone in a auto-refresh loop when using latest jquery.

Moreover, here, with PG11, even with the old jquery, the "Admin tests" fail on "3 - Check locks": There seems to be no lock, so that checking the table headers fails.

Does the tests run ok for you?

**Comment by xzilla** [comment]
You need to have $conf['show_system'] = true; for the locks page to show a lock, in order to have the start link show up (and then fail, like the processes page).

**Comment by nirgal** [comment]
Ops, thanks for the reminder about show_system.
The test problem was the toggle() was removed. Thanks selenium to have caught that on.
I took the time today to update to 1.9 with jquery-migrate-1 then to latest version. There's actually quite a few fixes. Enjoy!

**Comment by nirgal** [comment]
I refreshed the PR again, in order to minimize the deltas.

In the unlikely event that you could look at the PR 2 days ago, I could finally have the "delegated" on() working on dom elements that weren't created yet, so it is not necessary to move some code in the ajax success handler anymore.

After applying this patch, I suggest you replace all occurrences of "jQuery" by "$" in ``js/ac_insert_row.js`` and ``js/database.js``: This is the usual way, and this switch has already been made in several places.

**Pull request merged**
