### PR TITLE
Fix Functions error with PostgreSQL 11

### PR DESCRIPTION
**Pull request by twister65**
SQL error: p.proisagg does not exists.
Replace pg_proc.proisagg by pg_proc.prokind
PostgreSQL v11:
https://www.postgresql.org/docs/current/catalog-pg-proc.html

### CODE REVIEW

**Comment by twister65** [comment]
Hello, is there any still activity ?

**Comment by xzilla** [comment]
This commit suffers from the same problem as #58, except it now has the extra commit which undoes the changes, making things worse. We're going to track this issue in the other PR for now. That said, thank you for your submission!

**Comment by twister65** [comment]
The changes are placed in https://github.com/twister65/phppgadmin/blob/759ff824efdb1a58ca84ced96d473585de8135df/classes/database/Postgres11.php.
This is what the last commit does, it avoids a new issue with previous versions.

**Comment by xzilla** [comment]
Honestly, it is a bit hard to tell just what was being changed due to all the white space changes scattered in the commit, but looking at it closer, I see what you are going for. Unfortunately, this is actually backward... the way the dependencies work is that Postgres.php holds all the "standard" function calls usable across all versions, and only when we need to preserve a function call source for an old version do we move that function into the last needed version (which is then picked up by all older versions of Postgres). So in this case, the change we need is to move the existing function source into Postgres10.php, and put the new queries in Postgres.php. (At this point I've gone and looked at pg_proc, and 10/11 is where the change was introduced).

**Pull request closed without merging**
