### PR TITLE
Explicit Support for PG 9.5

### PR DESCRIPTION
**Pull request by crunchyjohn**

### CODE REVIEW

**Comment by HackG** [comment]
the sourceforge page says its only compatible up to 9.2 but it looks like this 9.5 support was committed?

`sudo apt-get install phppgadmin
`  
can anyone confirm installing from apt-get repo on Ubuntu would carry 9.5 compatibility?

**Comment by crunchyjohn** [comment]
Correct, Sourceforge only mentions that the project is compatible up to 9.2.  That is because the last tagged release of this project happened when 9.2 was active, and that was awhile ago.  There have been no tags since.  However, since then, there has been a commit for 9.3 support which has been merged to master, and a long time afterward, there was a commit for 9.4 support.  I'm honestly not sure why these haven't been put into a new release for this project; perhaps this project is mostly abandoned.  
  
I figured I'd send the 9.5 changes just so that they're there, if anyone wants to merge them to master, or to make a new release.  I am curious about the state of this project; is it basically stopped at 9.2, or are there plans for new tags?  
  
FWIW, 9.5 can be downloaded through this procedure (using apt-get):  
http://raonyguimaraes.com/installing-postgresql-9-5-on-linux/
although that's probably common knowledge.

**Comment by xzilla** [comment]
This has been merged :-)

**Comment by avnermiz** [comment]
Does anyone know if this will work with postgres 9.6? Thanks!

**Pull request closed without merging**
