### PR TITLE
Disable OID handling on PG12

### PR DESCRIPTION
**Pull request by nirgal**
Notes:
- "CREATE TABLE WITHOUT OIDS" continues to work, for now
- "SHOW default_with_oids" continues to work, for now

### CODE REVIEW

**Comment by nirgal** [comment]
I moved hasObjectID($table) from Postgres.php to Postgres11.php, and replaced it by a function always returning False.
Unfortunatly the function cannot be deleted because it's used in table exports (Should we ask or not whether to include the OIDS).

Also I added a var $supportOids in Postgres class, that is false from version 12 onward. It is used to hidden OID related GUI items when needed.

This should fix #67, #80 and #70 
Tested on PG12 only! (Untested on PG11 yet)

**Comment by nirgal** [comment]
It looks good on PG11.
I merged it on Debian, so that phppgadmin works with current version of postgres. I mean Browse is a major feature and needs to work.

**Comment by xzilla** [comment]
I've merged this into upstream and did some refactoring to make it more in-line with similar compatibility handling. See f40fcaa3dd89b5baf7c68b03e47618261960b872 and b7cf1b61cd87060afadbb51ba625697823ef51ad for details. I hope this doesn't cause too much trouble for debian users, and thanks again for the submissions.

**Comment by nirgal** [comment]
No trouble at all. Thank you for the new version! :)

**Pull request closed without merging**
