### PR TITLE
partial SQL execution failure

### PR DESCRIPTION
**Pull request by nirgal**
This is a fix for https://sourceforge.net/p/phppgadmin/bugs/448/ aka https://bugs.debian.org/762378

Thanks to Marc Dequènes for the bug report.

### CODE REVIEW

**Comment by xzilla** [comment]
Hey, I tried and failed to recreate this problem against git master; I see no reason that should be the case, but I'm wondering if you can make a self-contained test case, rather than have me try to make one based on the examples? Also curious what OS (from the users perspective, not the servers perspective) and version of php you folks are on.

**Comment by nirgal** [comment]
Hi

Here is a self-containted test file:

> CREATE TABLE table27 (test TEXT);
> INSERT INTO table27 VALUES ('line1');
> INSERT INTO table27 VALUES ('line2')
> ;
> INSERT INTO table27 VALUES ('line3');

Remember you need to save this in a sql file, then choose the file on the database "SQL" tab on top.
Line 4 of the sql file starts with a ';'.

The result is:
> CREATE TABLE
> INSERT 0 1
> INSERT 0 1
> 
>Temps d'exécution total : 639.032 ms
> 
>Requête SQL exécutée.

You can see there is only 2 INSERTs that were treated.
When browsing the table, you can see that there are only 2 records: line1 and line3.
Line2 was skiped.

I'm running php5 version 5.6.7, but I'm pretty sure the bug is there for all versions.

**Comment by nirgal** [comment]
One more thing in case you still can't reproduce the simple test case above, these tests were run on Debian GNU/Linux, meaning with unix style line separators.

**Comment by xzilla** [comment]
Heh, yes, seems simple but fascinatingly, that works fine for me:

````
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
Total runtime: 292.071 ms

SQL executed.
````

I'm working on osx 10.7.5, I don't think there is a line ending issue there.

**Comment by nirgal** [comment]
I just tried git master version, and I still can reproduce the problem.

I'm not sure you saw my previous comment updates above.

I added some logging in a branch:
https://github.com/nirgal/phppgadmin/commit/4fec0994d7a2b0a3bdbde5806dedd81c075a519e

Add here, on execution, I get:
> CREATE TABLE
> INSERT 0 1
> INTERNAL ERROR: disregarding INSERT INTO table27 VALUES ('line2') INSERT 0 1
> 
> Temps d'exécution total : 96.373 ms
> 
> Requête SQL exécutée.

**Comment by nirgal** [comment]
I added more debug information on my branch https://github.com/nirgal/phppgadmin/tree/issue_27_logging
including the file 27.sql I use.

Here's my output
```
strspn=0
strlen=28
DROP TABLE
strspn=0
strlen=32
CREATE TABLE
strspn=0
strlen=36
INSERT 0 1
strspn=0
strlen=0
INTERNAL ERROR: disregarding INSERT INTO table27 VALUES ('line2')
strspn=0
strlen=36
INSERT 0 1

Temps d'exécution total : 126.988 ms

Requête SQL exécutée.
```

I'd like to point out that April 1st is over here :p

**Comment by nirgal** [comment]
Ping?

I'm really surprised you don't have that issue. I'm ready to run any other test you can think of, just tell me.

FYI, I uploaded to Debian a version containing my patch.

**Comment by LuckySB** [comment]
wrong patch
error in place of "}" on line 7547

this close bracket should be on line 7527

    *** Postgres.php.orig   2015-05-14 15:33:55.989685043 +0300
    --- Postgres.php        2015-05-14 15:34:13.795684992 +0300
    ***************
    *** 7524,7529 ****
    --- 7524,7530 ----
                                            $query_buf .= "\n";
                                        /* append the line to the query buffer */
                                        $query_buf .= $subline;
    +                               }
                                        $query_buf .= ';';

                                                // Execute the query. PHP cannot execute
    ***************
    *** 7544,7550 ****
                                                }
                                        }
                                }
    -                       }

                                        $query_buf = null;
                                        $query_start = $i + $thislen;
    --- 7545,7550 ----

**Comment by nirgal** [comment]
Hi LuckySB.

"wrong patch" is a bit short a comment, but I guess this is better than nothing. :]

Could you confirm you can see the problem too? xzilla doesn't seem to be able to reproduce it.

Your patch proposal is indeed minimalist, but I think it is better to change the indentation, because with your version it's a bit more difficult to read... 

In your version of the patch, you now unconditionally run pg_query (line 7532).

However, the comment on the line immediately above says "Execute the query. PHP cannot execute empty queries, unlike libpq". So I wonder if that's wise?

In my version, I use `if (trim($query_buf))`. If the result is false, then there is no need to call pg_query.

**Pull request closed without merging**
