### PR TITLE
replaced old-style constructors (fixes php7 warnings)

### PR DESCRIPTION
**Pull request by gabrielhomsi**
Fixes "Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP..." messages

### CODE REVIEW

**Comment by mvrhov** [comment]
The addodb pull should be merged first.. and then some of the changes here are not needed anymore

**Comment by CodeBlastr** [comment]
Is this going to be merged anytime soon?  https://www.evernote.com/shard/s13/sh/16400aba-389e-471a-a93e-2d03400cc2af/07471f9f6abd6c71c1db79f9e88bef39

**Comment by Macbernie** [comment]
Good job @gabrielhomsi , your changes let us access to the phppgadmin portal.
But there is the same problem when we try to connect the PostgreSQL server.

**Comment by kavindakav** [comment]
Great job @gabrielhomsi  !! Thanks  This is very usefull !! Cheers

**Comment by kaynz** [comment]
+1 for merge!

**Comment by richp10** [comment]
Is a committer able to merge this PR - would be a great help.. 

Ta

**Comment by tontm1981** [comment]
I just downloaded the master branch version and these changes was not merged. And even with these changes, it is necessary to change child classes constructor. For example, class Postgres must have your constructor changed from "$this->ADODB_base($conn)" to "parent::__construct($conn)".

**Comment by richp10** [comment]
This is looking a little stale - most issues are fixed on forks such as: https://github.com/HuasoFoundries/phppgadmin

**Comment by JefferyHus** [comment]
is this pull even going to be merged??

**Comment by mikelolasagasti** [comment]
@JefferyHus your repo just contains one big commit with all phppgadmin + fixes, not the best way to work with git/github.

**Comment by JefferyHus** [comment]
@mikelolasagasti mate they have not merged the changes of @gabrielhomsi, so I have just fixed the issues put it in a repo so anyone will use it, once they merge the PR I will delete my repo, the fixes presented in this PR also is not the complete one I have kept testing all the classes and changed all parent calls of the constructors and the self constructor. yeah not the best way to play in git/github but at least a fix until they merge or do their own push. thanks anyway.

**Comment by dmitry-fedyuk** [comment]
The shortest fix is just to suppress the warning: https://df.tips/t/200

**Comment by JefferyHus** [comment]
@dmitry-fedyuk this won't help, it will just hide your errors while this errors means your phppg will not work.

**Comment by zschuessler** [comment]
Can a package maintainer chime in on if this will be merged?

Love the project, but it's being neglected at the moment. There are solutions to consider like adding another maintainer if time is an issue.

Barring that, anyone else want to consider their fork the new primary package? Quick review of the network graph suggests this one is most active:

https://github.com/HuasoFoundries/phppgadmin

**Comment by richp10** [comment]
I tried to use this project but under PHP 7.1 I could not make it work - just wanted to second the comment from @zschuessler - I use https://github.com/HuasoFoundries/phppgadmin which works with php7

Surely the efforts there could be merged in - and give HuasoFoundareis committ rights or something - this project is important enough for people to contribute but is fragmenting so efforts are dissipated.

**Comment by amenadiel** [comment]
I answered in https://github.com/HuasoFoundries/phppgadmin/issues/29
I don't know if it would be appropiate to rebrand my fork into a new project with a slightly different name.

But I would consider it if I had more contributors. My fork is still in beta. It has no tests, no documentation and I disabled the plugin sistem completely. I can't embrace the effort to complete those missing parts on my own.

**Comment by MurzNN** [comment]
Tested on Ubuntu Linux 16.04 & 18.04 with PHP 7.1 and 7.2 - works fine, please commit to HEAD.

**Comment by OmniTroid** [comment]
+1 please merge

**Comment by landzup** [comment]
Howdy guys,

after having installed this fork with no error, I sent my feedback like
yours too, telling that the replacement led to a working app.

But when started using it on Linux (Amazon EC2) with PHP 7.2.5 and
PostGreSQL 9.6.8, almost any function didn't work.

Some system info:

Server: Amazon Linux 2 (2017.12) LTS Release Candidate
pdo_pgsql enabled, PostgreSQL (libpq) Version: 9.2.23



​So I ask you if you can check main UI functionalities​ besides the
installation.
Most things in PHP 7 are retrocombatible with the version used in the
primary project library of PhpPgSQL, so I guess there's some work to be
done to make this fork stable.


Thanks


Cordiali Saluti / Kind Regards / Cordialement / Mit freundlichen Grüßen /
Saludos Cordiales / S pozdravem​
Emanuele del Grande



Il giorno mar 12 giu 2018 alle ore 10:12 David Skoland <
notifications@github.com> ha scritto:

**Comment by xzilla** [comment]
AFAICT, the changes suggested in this PR have all been addressed in the upstream repo. If you feel there are any remaining issues, please feel free to submit them in an updated / clean PR. Thanks for your effort/submission.

**Pull request closed without merging**
