### PR TITLE
PHP 7 and PostgreSQL 10 compatibility

### PR DESCRIPTION
**Pull request by y92**
In this code, I found several classes where the constructor function had the same name than the class. That is deprecated in PHP 7, and when I test this version on my machine, I get warning messages. The good way to define a constructor is to use the name __construct for the constructor.

Furthermore, the version 10.0 of PostgreSQL was released few days ago, and phpPgAdmin was not compatible with this new version of PgSQL, so I corrected this problem.

### CODE REVIEW

**Comment by fetus-hina** [comment]
The versioning method of PostgreSQL has been changed.
(Please check 4th paragraph of the [release announcement](https://www.postgresql.org/about/news/1786/))

The old method: `9.6` is a major version, `.0` is a minor version.
The new method: `10` is a major version, `.0` is a minor version.

So I think we should check "version 10", not "version 10.0".
Your code will be broken in the next patch release.

**Comment by y92** [comment]
I have just updated my repository so that it checks version 10 instead of 10.0

**Comment by SalahAdDin** [comment]
@y92 What's about `10.1` version?

**Comment by y92** [comment]
Normally it works with postgresql 10.1 version.

**Pull request closed without merging**
